language: go

services:
  - docker

before_install:
  - docker pull mongo:3.4.3
  - docker run -d -p 127.0.0.1:27017:27017 mongo:3.4.3 --storageEngine=wiredTiger
  - wget "https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz"
  - mkdir -p $HOME/bin
  - tar -vxz -C $HOME/bin --strip=1 -f glide-v0.12.3-linux-amd64.tar.gz
  - export PATH="$HOME/bin:$PATH"

install: make install

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list;
    sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3;
    curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -;
    sudo apt-get install -y -qq nodejs yarn;
    cd web && yarn install --ignore-engines && cd -;
    make build;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push blankrobot/pulpe;
    fi

go:
  - 1.8

script:
  - make testrace
