FROM golang:1.8.1

RUN curl https://glide.sh/get | sh

COPY . /go/src/github.com/blankrobot/pulpe/

WORKDIR /go/src/github.com/blankrobot/pulpe/

RUN glide install

CMD CGO_ENABLED=0 GOOS=linux go build -o /dist/pulpe -a -installsuffix cgo ./cmd/pulpe
